export const exportKinds = [
  "people",
  "affiliations",
  "relationships",
  "companies",
  "needs",
  "evidence",
  "capabilities",
  "partnerships",
  "previousOutreach",
  "opportunities",
  "assessments",
  "reviews",
  "activities",
  "outcomes",
  "aiRuns",
  "generationRuns",
  "importSummaries",
  "incentives",
] as const;
